<MainScreen>:
    GridLayout:
        cols:1
        padding: 3
        spacing: 3
        Image:
            id:img
            size_hint_y: 80
        TextInput:
            id: user_query
            size_hint_y: 10
        Button:
            text: 'Search Image'
            size_hint_y: 10
            on_press:root.set_image()

<RootWidget>:
    MainScreen:
        id: main_screen
        name: 'Main Screen'